### ISSUE TITLE
No result on bulk annotation and Image map annotation for any image under idr0015

### ISSUE THREAD

**Issue by Rettwo** [IDR/idr0015-colin-taraoceans#1]
MAP_URL = "{base}/webclient/api/annotations/?type=map&{type}={image_id}"

IMAGE_ID = #image_id under idr0015

qs = {'base': IDR_BASE_URL, 
      'type': 'image', 
      'image_id': IMAGE_ID}

url = MAP_URL.format(**qs)
for a in session.get(url).json()['annotations']:
    namespace = a['ns']
    for v in a['values']:
        key = v[0]
        value = v[1]
        print(key, value)

**Comment by jburel** [comment]
@Rettwo Thanks for opening an issue.
This is an early study that we did not have much annotation for the images provided by the authors.
the information provided has been put at the study level. They have been used to build a notebook see https://github.com/jburel/idr0015-colin-taraoceans/blob/notebooks/notebooks/Tara_Oceans_Geospatial.ipynb). Note that some info needs to be updated (there are a few positive values for the location that should have been set to negative values)
